#!/usr/bin/env python3
"""Generate web/config.js from include/secret.h.

The firmware and the dashboard talk to the same Supabase project, so they
should not each carry their own copy of the URL and key -- one gets updated,
the other does not, and the symptom is a dashboard that reads an empty
database while the devices happily write to a different one.

    python tools/make_web_config.py                     # anonymous sign-in
    python tools/make_web_config.py --email a@b.c --password s3cret
    python tools/make_web_config.py --manual-login      # show the sign-in form

secret.h is gitignored and so is the config.js this writes. Neither is ever
printed to the terminal: this script reports lengths, not values.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SECRET = ROOT / "include" / "secret.h"
OUT = ROOT / "web" / "config.js"

# #define NAME "value", tolerating escaped quotes inside the string.
DEFINE = re.compile(r'^\s*#\s*define\s+(\w+)\s+"((?:[^"\\]|\\.)*)"', re.MULTILINE)

BANNER = """// GENERATED by tools/make_web_config.py from include/secret.h -- do not edit.
// Gitignored: it holds the live anon key. Re-run the script after changing
// secret.h. The template and the meaning of each field: config.example.js
"""


def read_defines(path: Path) -> dict[str, str]:
    if not path.exists():
        sys.exit(
            f"{path} not found.\n"
            f"Copy include/secret.h.example to include/secret.h and fill it in."
        )
    text = path.read_text(encoding="utf-8", errors="replace")
    return {m.group(1): m.group(2).encode().decode("unicode_escape") for m in DEFINE.finditer(text)}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--email", help="sign in silently as this account instead of anonymously")
    mode.add_argument("--manual-login", action="store_true",
                      help="show the sign-in form rather than authenticating automatically")
    ap.add_argument("--password", help="password for --email")
    args = ap.parse_args()

    if args.email and not args.password:
        sys.exit("--email needs --password")

    d = read_defines(SECRET)
    url = (d.get("SUPABASE_URL") or "").rstrip("/")
    key = d.get("SUPABASE_ANON_KEY") or ""

    missing = [n for n, v in (("SUPABASE_URL", url), ("SUPABASE_ANON_KEY", key)) if not v]
    if missing:
        sys.exit(f"{SECRET} has no value for: {', '.join(missing)}")

    # The service_role key is a JWT whose payload names the role. Catching it
    # here is worth the four lines: pasted into a browser it would hand every
    # visitor BYPASSRLS, and nothing downstream would complain.
    if '"role":"service_role"' in _jwt_payload(key):
        sys.exit(
            "SUPABASE_ANON_KEY in secret.h is the SERVICE_ROLE key, not the anon key.\n"
            "It carries BYPASSRLS and must never reach a browser or a device."
        )

    if args.manual_login:
        auto = None
    elif args.email:
        auto = {"email": args.email, "password": args.password}
    else:
        auto = "anonymous"

    body = {"url": url, "anonKey": key, "autoLogin": auto}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        BANNER + "window.BOWLSTACK_CONFIG = " + json.dumps(body, indent=2) + ";\n",
        encoding="utf-8",
    )

    described = ("the sign-in form" if auto is None
                 else "anonymous sign-in" if auto == "anonymous"
                 else f"sign-in as {args.email}")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"  url        {url}")
    print(f"  anon key   {len(key)} chars, ending {key[-6:]}")
    print(f"  auth       {described}")
    if auto == "anonymous":
        print("\nTurn ON Authentication -> Sign In / Providers -> "
              "'Allow anonymous sign-ins' in the Supabase dashboard,\n"
              "or the dashboard will load with no data.")
    return 0


def _jwt_payload(token: str) -> str:
    import base64
    parts = token.split(".")
    if len(parts) < 2:
        return ""
    seg = parts[1]
    seg += "=" * (-len(seg) % 4)
    try:
        return base64.urlsafe_b64decode(seg).decode("utf-8", "replace").replace(" ", "")
    except Exception:
        return ""


if __name__ == "__main__":
    raise SystemExit(main())
